# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_infected_neighbors_rcpp <- function(infection_matrix, i, j) {
    .Call(`_ForestFire_find_infected_neighbors_rcpp`, infection_matrix, i, j)
}

forest_fire_rcpp <- function(infection_matrix, alpha, beta, pausing) {
    .Call(`_ForestFire_forest_fire_rcpp`, infection_matrix, alpha, beta, pausing)
}

rcpp_hello_world <- function() {
    .Call(`_ForestFire_rcpp_hello_world`)
}

